create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  path text not null,
  referrer text,
  user_agent text,
  ip_hash text,
  country text,
  region text,
  city text,
  screen text,
  language text,
  timezone text,
  source text
);

create index if not exists visits_created_at_idx on public.visits (created_at desc);
create index if not exists visits_path_idx on public.visits (path);
create index if not exists visits_ip_hash_idx on public.visits (ip_hash);

