import fs from "node:fs";
import path from "node:path";

import { notesOutline } from "../app/notes/outline";

type GeneratedNotesModule = {
  noteSourceById: Record<string, string>;
  noteUpdatedAtById: Record<string, string>;
};

const toIsoDate = (date: Date) => date.toISOString().slice(0, 10);

const readFileOrEmpty = (relativePath: string) => {
  try {
    return fs.readFileSync(path.join(process.cwd(), relativePath), "utf8").trim();
  } catch {
    return "";
  }
};

const mtimeOrToday = (relativePath: string) => {
  try {
    const stat = fs.statSync(path.join(process.cwd(), relativePath));
    return toIsoDate(new Date(stat.mtime));
  } catch {
    return toIsoDate(new Date());
  }
};

const buildGeneratedNotes = (): GeneratedNotesModule => {
  const noteSourceById: Record<string, string> = {};
  const noteUpdatedAtById: Record<string, string> = {};

  const items = notesOutline.flatMap((g) => g.items);
  for (const item of items) {
    noteSourceById[item.id] = readFileOrEmpty(item.markdownPath);
    noteUpdatedAtById[item.id] = mtimeOrToday(item.markdownPath);
  }

  return { noteSourceById, noteUpdatedAtById };
};

const writeGeneratedModule = (outPath: string, data: GeneratedNotesModule) => {
  const header = `// This file is generated by scripts/generate-notes.ts\n\n`;
  const body =
    `export const noteSourceById = ${JSON.stringify(data.noteSourceById)} as const;\n` +
    `export const noteUpdatedAtById = ${JSON.stringify(data.noteUpdatedAtById)} as const;\n`;

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, header + body, "utf8");
};

const main = () => {
  const outFile = path.join(
    process.cwd(),
    "app/notes/generated/notes.generated.ts"
  );
  writeGeneratedModule(outFile, buildGeneratedNotes());
  // eslint-disable-next-line no-console
  console.log(`Generated: ${path.relative(process.cwd(), outFile)}`);
};

main();
